services:
  app:
    build: .
    ports:
      - "4000:4000"
    environment:
      PHX_SERVER: "true"
      PHX_HOST: "localhost"
      PHX_SCHEME: "http"
      PHX_URL_PORT: "4000"
      PORT: "4000"
      DATABASE_PATH: "/data/inkit.db"
      UPLOAD_DIR: "/data/uploads"
      SECRET_KEY_BASE: "r6qhwgJmhh/WBzy9fd+AW+/7JB26wCwIEJW6z4F4u2bikp4Z4Lf7ANnJyuee7jKS"
    volumes:
      - inkit_data:/data

volumes:
  inkit_data:
