defmodule Inkit.Repo.Migrations.AddRetentionResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:retention_settings, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :interval_minutes, :bigint, null: false
      add :images_days, :bigint, null: false
      add :api_logs_days, :bigint, null: false
      add :messages_days, :bigint, null: false
      add :enabled, :boolean, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:retention_runs, primary_key: false) do
      add :inserted_at, :utc_datetime_usec, null: false
      add :error_message, :text
      add :images_deleted, :bigint, null: false
      add :api_logs_deleted, :bigint, null: false
      add :messages_deleted, :bigint, null: false
      add :triggered_by, :text, null: false
      add :status, :text, null: false
      add :duration_ms, :bigint, null: false
      add :finished_at, :utc_datetime_usec, null: false
      add :started_at, :utc_datetime_usec, null: false
      add :id, :uuid, null: false, primary_key: true
    end
  end

  def down do
    drop table(:retention_runs)

    drop table(:retention_settings)
  end
end
