defmodule Inkit.Repo.Migrations.AddApiLogs do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:api_logs, primary_key: false) do
      add :inserted_at, :utc_datetime_usec, null: false
      add :image_public_id, :text
      add :duration_ms, :bigint, null: false
      add :status, :bigint, null: false
      add :path, :text, null: false
      add :method, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end
  end

  def down do
    drop table(:api_logs)
  end
end
