defmodule Inkit.Repo.Migrations.CreateVisualAssistant do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:uploaded_images, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :sha256, :text, null: false
      add :storage_path, :text, null: false
      add :size, :bigint, null: false
      add :content_type, :text, null: false
      add :original_filename, :text, null: false
      add :public_id, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:uploaded_images, [:public_id],
             name: "uploaded_images_unique_public_id_index"
           )

    create table(:conversation_messages, primary_key: false) do
      add :uploaded_image_id,
          references(:uploaded_images,
            column: :id,
            name: "conversation_messages_uploaded_image_id_fkey",
            type: :uuid
          ),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :response_id, :text
      add :content, :text, null: false
      add :role, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end
  end

  def down do
    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `conversation_messages` table without the `conversation_messages_uploaded_image_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:conversation_messages)

    drop_if_exists unique_index(:uploaded_images, [:public_id],
                     name: "uploaded_images_unique_public_id_index"
                   )

    drop table(:uploaded_images)
  end
end
