apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: inkit-data
  namespace: inkit
  labels:
    app.kubernetes.io/name: inkit
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

