apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: carverauto-web-gateway
  namespace: carverauto-web
spec:
  gatewayClassName: carverauto-web-envoy
  listeners:
    - name: https-inkit
      hostname: inkit.carverauto.dev
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - group: ""
            kind: Secret
            name: inkit-tls
      allowedRoutes:
        namespaces:
          from: Same
