apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: inkit
  namespace: carverauto-web
  annotations:
    external-dns.alpha.kubernetes.io/hostname: inkit.carverauto.dev
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: carverauto-web-gateway
      sectionName: https-inkit
  hostnames:
    - inkit.carverauto.dev
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - group: ""
          kind: Service
          name: inkit
          namespace: inkit
          port: 80
          weight: 1
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: inkit-http-redirect
  namespace: carverauto-web
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: carverauto-web-gateway
      sectionName: http
  hostnames:
    - inkit.carverauto.dev
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
