---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: inkit-runtime
  namespace: inkit
spec:
  encryptedData:
    SECRET_KEY_BASE: AgCDCBNeCIKiKXFo03iVCEbEto7pyaNK0RaIdJpXveMvbs7J+AwcyKJuRbQuSUG6xFQBbfu71DG/mrIsBwJtWoGG2mC5XDRZmZvjEaAkX3Y8A9NTwgW6DMtOIiwx/Rzeccn6OCQlnFvIXiLcgcJTqrJBPE2Xe/s/LahDY+Td8QIYGGcnWNXSD1/P4bFv84P96WX3vGAX/zCxtLm1LnMbYqVmcLVMdTW0CyOXMDKLi0nEHULmwRMIAErtY5Ypon1ZDT2LcJrN0Vqd/ajcnLCM7mG1rYmxmY5QAte7qQrjJtxhmtmeHF6mRfmv6SFtWslY1Y7zDccKtHWA6EgprB4YNdho8N4V+x4tZYvT+0Hv1ihg0ty5TYxrBFploar1jQBKzWeynwoN77gsKlf+S6DeVUOOVUuLSg9UpP5Z2X3JD0XB0K8BHqTBMlHJg4bQrxAwK9sZBktCqvu76k1sVAf2lcaerinUgEh5R9Qt6+4/KQcaMTNnH19omJjYaUz9TGyeGTr+WcGiBi9YIeOP0eusoi/T/DMW9hVbpsM8kYzS2Qs8Gtu744ktWaaolepWCgCfbTue+oVcU9/qB8GXUghADPtoUQ/PIjPFv4cvIwAkh1Vd9+YZtlCM39FbWN569Phhi9GZqHjshVI/EKKNp4OlqIE90e6Ygi45mBbI0fxULDGhAkU2IZa+czHS6ytofvXb3u68J+zMTMiVoUYVl+dMm3ybgeOIlvwu2pIQ2eiNCA8AuNdUgg2ofP5J5GzvBMgUh9oL6gDhyCUg2a9650cHwSG8
  template:
    metadata:
      name: inkit-runtime
      namespace: inkit
