---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: inkit-runtime
  namespace: inkit
spec:
  encryptedData:
    SECRET_KEY_BASE: AgA+tDoFSnnBcpRzgPOZyQ6Ywhd+wk9qIZq6fQqvwtgtNwLAFpGPXzIelTY94005bJwmnM3BsbXXAd4RyGSwQMOfHWcLCSCnTeo0DRZjOpqpaQnRyR99CoZ1I6uIR9PMfZ2c+SZS0YHj3UobRLha/l4uBDQzNvFlYgWPLXLcAZZ2RmdIV3LZlnWfx+tOehTcmM4rGhtdY27ZKjIhXQDK6ALxr+NMTrslyygQ4bC3BN+ymaDqcSLeReanCx7L/vaSzwxdCzEgI/XsMS5Qem6u7hiEm0bTHgzU4YqZGSWPWq5+pPn6j41eMntaF+fKYxtnyvXW8v4S8YiSigAU7DSlojdY9LSUk/UCrk0s4aeCM34a5QBMOLJExm8TyoJk0aRywJVT5evBo53x8bghF/HZcO4z/Ra2bp53WP2v5VAREO7S1LDan5xwxlwYHuDEKj9subwzNCiUFiZ21UFgKhgYkijUMZ4p1XmAP0IT4DPPpzTFFt39p/S19KQDicxX/df7mcc56nvysb93yUCbWK7a0tdtx1H6vIlV/taY3UON8EcrEI2aiZsuV3rsw8TR5thSq+zsIvKIVao7uoB36XWhJ1FtKDK689cUaSBziDAadWOaBWFwd5C5gYb4sge8kOoA+KEM/vpfFHhp75KtQvuPzAZ0zRTggV2evQKSvwat2gTUg9+GISEOdDvoH46Rji4PoWzG2BEBlCQbEpstX9CtmXJFIRRRTSqcsE/4QS6J8uwsmCJI5GYbN7n5jVa+5IycTiHCQfcU91bHN
  template:
    metadata:
      name: inkit-runtime
      namespace: inkit
